"""Question banks for tebak-tebakan minigames. Each entry has `q` (question),
`a` (correct answer), and `f` (list of fake answers used to fill 4 choices)."""

FLAGS = [
    {"q": "🇮🇩", "a": "Indonesia", "f": ["Malaysia", "Singapura", "Filipina"]},
    {"q": "🇯🇵", "a": "Jepang", "f": ["Korea Selatan", "China", "Vietnam"]},
    {"q": "🇰🇷", "a": "Korea Selatan", "f": ["Korea Utara", "Jepang", "Mongolia"]},
    {"q": "🇺🇸", "a": "Amerika Serikat", "f": ["Inggris", "Kanada", "Australia"]},
    {"q": "🇬🇧", "a": "Inggris", "f": ["Amerika", "Irlandia", "Australia"]},
    {"q": "🇫🇷", "a": "Prancis", "f": ["Belanda", "Italia", "Belgia"]},
    {"q": "🇩🇪", "a": "Jerman", "f": ["Belgia", "Belanda", "Polandia"]},
    {"q": "🇮🇹", "a": "Italia", "f": ["Spanyol", "Prancis", "Portugal"]},
    {"q": "🇪🇸", "a": "Spanyol", "f": ["Italia", "Portugal", "Meksiko"]},
    {"q": "🇧🇷", "a": "Brasil", "f": ["Argentina", "Portugal", "Meksiko"]},
    {"q": "🇦🇷", "a": "Argentina", "f": ["Brasil", "Chile", "Uruguay"]},
    {"q": "🇨🇦", "a": "Kanada", "f": ["Amerika", "Inggris", "Australia"]},
    {"q": "🇦🇺", "a": "Australia", "f": ["Selandia Baru", "Inggris", "Afrika Selatan"]},
    {"q": "🇨🇳", "a": "China", "f": ["Vietnam", "Jepang", "Mongolia"]},
    {"q": "🇮🇳", "a": "India", "f": ["Pakistan", "Bangladesh", "Sri Lanka"]},
    {"q": "🇸🇦", "a": "Arab Saudi", "f": ["Mesir", "Iran", "Yaman"]},
    {"q": "🇹🇷", "a": "Turki", "f": ["Yunani", "Iran", "Mesir"]},
    {"q": "🇷🇺", "a": "Rusia", "f": ["Belanda", "Luksemburg", "Ukraina"]},
    {"q": "🇲🇽", "a": "Meksiko", "f": ["Italia", "Spanyol", "Brasil"]},
    {"q": "🇳🇱", "a": "Belanda", "f": ["Rusia", "Prancis", "Luksemburg"]},
    {"q": "🇸🇪", "a": "Swedia", "f": ["Norwegia", "Finlandia", "Denmark"]},
    {"q": "🇳🇴", "a": "Norwegia", "f": ["Swedia", "Denmark", "Islandia"]},
    {"q": "🇨🇭", "a": "Swiss", "f": ["Austria", "Jerman", "Belgia"]},
    {"q": "🇧🇪", "a": "Belgia", "f": ["Jerman", "Belanda", "Prancis"]},
    {"q": "🇵🇹", "a": "Portugal", "f": ["Spanyol", "Italia", "Brasil"]},
    {"q": "🇬🇷", "a": "Yunani", "f": ["Turki", "Italia", "Spanyol"]},
    {"q": "🇪🇬", "a": "Mesir", "f": ["Maroko", "Sudan", "Libya"]},
    {"q": "🇿🇦", "a": "Afrika Selatan", "f": ["Mesir", "Nigeria", "Kenya"]},
    {"q": "🇹🇭", "a": "Thailand", "f": ["Vietnam", "Kamboja", "Laos"]},
    {"q": "🇻🇳", "a": "Vietnam", "f": ["Thailand", "Kamboja", "Laos"]},
    {"q": "🇵🇭", "a": "Filipina", "f": ["Indonesia", "Malaysia", "Vietnam"]},
    {"q": "🇸🇬", "a": "Singapura", "f": ["Malaysia", "Indonesia", "Brunei"]},
    {"q": "🇲🇾", "a": "Malaysia", "f": ["Indonesia", "Brunei", "Singapura"]},
    {"q": "🇳🇿", "a": "Selandia Baru", "f": ["Australia", "Inggris", "Kanada"]},
    {"q": "🇺🇦", "a": "Ukraina", "f": ["Rusia", "Belarus", "Polandia"]},
    {"q": "🇵🇱", "a": "Polandia", "f": ["Jerman", "Ceko", "Slovakia"]},
]

KPOP = [
    {"q": "RM, Jin, Suga, J-Hope, Jimin, V, Jungkook", "a": "BTS", "f": ["EXO", "SEVENTEEN", "BIGBANG"]},
    {"q": "Jennie, Jisoo, Rosé, Lisa", "a": "BLACKPINK", "f": ["TWICE", "Red Velvet", "ITZY"]},
    {"q": "Nayeon, Jeongyeon, Momo, Sana, Jihyo, Mina, Dahyun, Chaeyoung, Tzuyu", "a": "TWICE", "f": ["BLACKPINK", "Girls' Generation", "ITZY"]},
    {"q": "Karina, Giselle, Winter, Ningning", "a": "aespa", "f": ["IVE", "NewJeans", "ITZY"]},
    {"q": "Minji, Hanni, Danielle, Haerin, Hyein", "a": "NewJeans", "f": ["LE SSERAFIM", "IVE", "aespa"]},
    {"q": "Sakura, Chaewon, Yunjin, Kazuha, Eunchae", "a": "LE SSERAFIM", "f": ["NewJeans", "IVE", "ITZY"]},
    {"q": "Yujin, Gaeul, Rei, Wonyoung, Liz, Leeseo", "a": "IVE", "f": ["aespa", "NewJeans", "ITZY"]},
    {"q": "Yeji, Lia, Ryujin, Chaeryeong, Yuna", "a": "ITZY", "f": ["aespa", "IVE", "ILLIT"]},
    {"q": "Soyeon, Miyeon, Minnie, Yuqi, Shuhua", "a": "(G)I-DLE", "f": ["IZ*ONE", "EVERGLOW", "MAMAMOO"]},
    {"q": "Solar, Moonbyul, Wheein, Hwasa", "a": "MAMAMOO", "f": ["Brown Eyed Girls", "Red Velvet", "EXID"]},
    {"q": "Irene, Seulgi, Wendy, Joy, Yeri", "a": "Red Velvet", "f": ["TWICE", "Girls' Generation", "f(x)"]},
    {"q": "Taeyeon, Tiffany, Yoona, Hyoyeon, Sunny, Yuri, Sooyoung, Seohyun", "a": "Girls' Generation", "f": ["After School", "Wonder Girls", "KARA"]},
    {"q": "Xiumin, Suho, Lay, Baekhyun, Chen, Chanyeol, D.O., Kai, Sehun", "a": "EXO", "f": ["BTS", "SHINee", "NCT 127"]},
    {"q": "Onew, Key, Minho, Taemin", "a": "SHINee", "f": ["EXO", "Super Junior", "BIGBANG"]},
    {"q": "G-Dragon, T.O.P, Taeyang, Daesung", "a": "BIGBANG", "f": ["Super Junior", "EXO", "2PM"]},
    {"q": "S.Coups, Jeonghan, Joshua, Jun, Hoshi, Wonwoo, Woozi, DK, Mingyu, The8, Seungkwan, Vernon, Dino", "a": "SEVENTEEN", "f": ["NCT", "Stray Kids", "ATEEZ"]},
    {"q": "Bang Chan, Lee Know, Changbin, Hyunjin, Han, Felix, Seungmin, I.N", "a": "Stray Kids", "f": ["ENHYPEN", "ATEEZ", "TXT"]},
    {"q": "Heeseung, Jay, Jake, Sunghoon, Sunoo, Jungwon, Ni-ki", "a": "ENHYPEN", "f": ["TXT", "Stray Kids", "TREASURE"]},
    {"q": "Soobin, Yeonjun, Beomgyu, Taehyun, Hueningkai", "a": "TXT", "f": ["ENHYPEN", "BTS", "ATEEZ"]},
    {"q": "Hongjoong, Seonghwa, Yunho, Yeosang, San, Mingi, Wooyoung, Jongho", "a": "ATEEZ", "f": ["Stray Kids", "ENHYPEN", "TREASURE"]},
]

WORDS = [
    {"q": "Perasaan rindu yang mendalam pada masa lalu.", "a": "Nostalgia", "f": ["Melankolis", "Apatis", "Antusias"]},
    {"q": "Sikap acuh tak acuh atau tidak peduli.", "a": "Apatis", "f": ["Empati", "Simpati", "Skeptis"]},
    {"q": "Orang yang ahli dalam suatu bidang tertentu.", "a": "Pakar", "f": ["Amatir", "Pemula", "Awam"]},
    {"q": "Keadaan tidak tetap atau mudah berubah.", "a": "Labil", "f": ["Stabil", "Konsisten", "Permanen"]},
    {"q": "Penilaian atau prasangka sebelum mengetahui faktanya.", "a": "Stereotip", "f": ["Stigma", "Mitos", "Hipotesis"]},
    {"q": "Sesuatu yang sangat besar atau hebat.", "a": "Kolosal", "f": ["Kompak", "Modular", "Marginal"]},
    {"q": "Cara berpikir yang masuk akal dan berdasar bukti.", "a": "Logis", "f": ["Naluriah", "Mistis", "Spontan"]},
    {"q": "Orang yang membenci atau memandang rendah lawan jenis.", "a": "Misoginis", "f": ["Misantropi", "Narsistik", "Egois"]},
    {"q": "Rasa takut berlebihan terhadap ruang sempit.", "a": "Klaustrofobia", "f": ["Akrofobia", "Agorafobia", "Hidrofobia"]},
    {"q": "Sifat suka memamerkan diri atau pencapaian.", "a": "Narsistik", "f": ["Egois", "Sombong", "Ambisius"]},
    {"q": "Keinginan kuat untuk mencapai sesuatu.", "a": "Ambisi", "f": ["Obsesi", "Motivasi", "Aspirasi"]},
    {"q": "Orang yang suka menyendiri dan menghindari keramaian.", "a": "Introvert", "f": ["Ekstrovert", "Ambivert", "Apatis"]},
    {"q": "Pernyataan yang bertentangan tapi mengandung kebenaran.", "a": "Paradoks", "f": ["Hipotesis", "Anekdot", "Metafora"]},
    {"q": "Perasaan iri pada keberhasilan orang lain.", "a": "Dengki", "f": ["Empati", "Simpati", "Apatis"]},
    {"q": "Kebiasaan menunda-nunda pekerjaan.", "a": "Prokrastinasi", "f": ["Impulsivitas", "Diskriminasi", "Frustrasi"]},
    {"q": "Sikap menerima keadaan apa adanya.", "a": "Pasrah", "f": ["Ambisius", "Optimis", "Resisten"]},
    {"q": "Berbicara berlebihan atau membual.", "a": "Hiperbola", "f": ["Metafora", "Personifikasi", "Sinestesia"]},
    {"q": "Merasa lebih unggul dari orang lain.", "a": "Arogan", "f": ["Rendah hati", "Empati", "Apatis"]},
    {"q": "Penilaian buruk yang melekat pada seseorang.", "a": "Stigma", "f": ["Stereotip", "Diskriminasi", "Apatis"]},
    {"q": "Keinginan untuk berbuat baik tanpa pamrih.", "a": "Altruisme", "f": ["Hedonisme", "Egoisme", "Skeptisisme"]},
]

CAPITALS = [
    {"q": "Indonesia", "a": "Jakarta", "f": ["Bandung", "Surabaya", "Medan"]},
    {"q": "Jepang", "a": "Tokyo", "f": ["Osaka", "Kyoto", "Yokohama"]},
    {"q": "Korea Selatan", "a": "Seoul", "f": ["Busan", "Incheon", "Daegu"]},
    {"q": "Prancis", "a": "Paris", "f": ["Lyon", "Marseille", "Nice"]},
    {"q": "Inggris", "a": "London", "f": ["Manchester", "Liverpool", "Birmingham"]},
    {"q": "Jerman", "a": "Berlin", "f": ["Munich", "Hamburg", "Frankfurt"]},
    {"q": "Italia", "a": "Roma", "f": ["Milan", "Venesia", "Florence"]},
    {"q": "Spanyol", "a": "Madrid", "f": ["Barcelona", "Valencia", "Seville"]},
    {"q": "Australia", "a": "Canberra", "f": ["Sydney", "Melbourne", "Brisbane"]},
    {"q": "Brasil", "a": "Brasilia", "f": ["Rio de Janeiro", "São Paulo", "Salvador"]},
    {"q": "Argentina", "a": "Buenos Aires", "f": ["Córdoba", "Rosario", "La Plata"]},
    {"q": "Kanada", "a": "Ottawa", "f": ["Toronto", "Vancouver", "Montreal"]},
    {"q": "Mesir", "a": "Kairo", "f": ["Alexandria", "Giza", "Luxor"]},
    {"q": "India", "a": "New Delhi", "f": ["Mumbai", "Kolkata", "Bangalore"]},
    {"q": "Turki", "a": "Ankara", "f": ["Istanbul", "Izmir", "Bursa"]},
    {"q": "Rusia", "a": "Moskow", "f": ["Saint Petersburg", "Novosibirsk", "Kazan"]},
    {"q": "Filipina", "a": "Manila", "f": ["Cebu", "Davao", "Quezon City"]},
    {"q": "Vietnam", "a": "Hanoi", "f": ["Ho Chi Minh", "Da Nang", "Hue"]},
    {"q": "Thailand", "a": "Bangkok", "f": ["Chiang Mai", "Pattaya", "Phuket"]},
    {"q": "Belanda", "a": "Amsterdam", "f": ["Rotterdam", "Den Haag", "Utrecht"]},
    {"q": "Yunani", "a": "Athena", "f": ["Sparta", "Thessaloniki", "Piraeus"]},
    {"q": "Afrika Selatan", "a": "Pretoria", "f": ["Cape Town", "Johannesburg", "Durban"]},
    {"q": "Arab Saudi", "a": "Riyadh", "f": ["Jeddah", "Mekkah", "Madinah"]},
    {"q": "Selandia Baru", "a": "Wellington", "f": ["Auckland", "Christchurch", "Hamilton"]},
    {"q": "Polandia", "a": "Warsawa", "f": ["Krakow", "Gdansk", "Lodz"]},
]

ANIMALS = [
    {"q": "Hewan terbesar di laut.", "a": "Paus Biru", "f": ["Hiu Putih", "Lumba-lumba", "Orca"]},
    {"q": "Burung yang tidak bisa terbang dan hidup di Antartika.", "a": "Penguin", "f": ["Burung Unta", "Albatros", "Kiwi"]},
    {"q": "Hewan tercepat di darat.", "a": "Cheetah", "f": ["Singa", "Macan Tutul", "Antelop"]},
    {"q": "Mamalia yang bisa terbang.", "a": "Kelelawar", "f": ["Tupai", "Burung", "Ngengat"]},
    {"q": "Hewan yang tidur paling lama dalam sehari.", "a": "Koala", "f": ["Sloth", "Kucing", "Beruang"]},
    {"q": "Reptil terbesar di dunia.", "a": "Buaya Air Asin", "f": ["Komodo", "Anaconda", "Iguana Hijau"]},
    {"q": "Hewan dengan leher terpanjang.", "a": "Jerapah", "f": ["Unta", "Kuda", "Llama"]},
    {"q": "Serangga yang menghasilkan madu.", "a": "Lebah", "f": ["Tawon", "Semut", "Lalat"]},
    {"q": "Hewan dengan delapan tentakel.", "a": "Gurita", "f": ["Cumi-cumi", "Sotong", "Ubur-ubur"]},
    {"q": "Mamalia bertelur dari Australia.", "a": "Platipus", "f": ["Echidna", "Koala", "Wombat"]},
    {"q": "Predator puncak di savana Afrika.", "a": "Singa", "f": ["Harimau", "Macan Tutul", "Cheetah"]},
    {"q": "Hewan yang berganti warna kulit.", "a": "Bunglon", "f": ["Iguana", "Tokek", "Salamander"]},
    {"q": "Mamalia laut paling cerdas.", "a": "Lumba-lumba", "f": ["Paus", "Anjing Laut", "Hiu"]},
    {"q": "Hewan nasional Indonesia.", "a": "Komodo", "f": ["Garuda", "Harimau Sumatra", "Burung Cendrawasih"]},
    {"q": "Burung yang tidak bisa terbang dari Selandia Baru.", "a": "Kiwi", "f": ["Penguin", "Kasuari", "Emu"]},
    {"q": "Mamalia darat terbesar.", "a": "Gajah Afrika", "f": ["Badak Putih", "Hipopotamus", "Jerapah"]},
    {"q": "Hewan yang bisa beregenerasi anggota tubuhnya.", "a": "Salamander", "f": ["Kadal", "Cacing", "Bintang Laut"]},
    {"q": "Predator yang sering disebut raja hutan.", "a": "Singa", "f": ["Harimau", "Beruang", "Serigala"]},
]

GREETINGS = [
    {"q": "Konnichiwa", "a": "Jepang", "f": ["Korea", "China", "Vietnam"]},
    {"q": "Annyeonghaseyo", "a": "Korea", "f": ["Jepang", "Mongolia", "Vietnam"]},
    {"q": "Bonjour", "a": "Prancis", "f": ["Italia", "Spanyol", "Portugal"]},
    {"q": "Hola", "a": "Spanyol", "f": ["Italia", "Portugal", "Prancis"]},
    {"q": "Ciao", "a": "Italia", "f": ["Spanyol", "Prancis", "Portugal"]},
    {"q": "Guten Tag", "a": "Jerman", "f": ["Belanda", "Swedia", "Denmark"]},
    {"q": "Olá", "a": "Portugal", "f": ["Spanyol", "Italia", "Prancis"]},
    {"q": "Namaste", "a": "India", "f": ["Nepal", "Sri Lanka", "Bangladesh"]},
    {"q": "Salam alaikum", "a": "Arab", "f": ["Persia", "Turki", "Urdu"]},
    {"q": "Ni hao", "a": "China", "f": ["Vietnam", "Mongolia", "Korea"]},
    {"q": "Sawasdee", "a": "Thailand", "f": ["Vietnam", "Kamboja", "Laos"]},
    {"q": "Xin chào", "a": "Vietnam", "f": ["Thailand", "Kamboja", "Laos"]},
    {"q": "Hej", "a": "Swedia", "f": ["Denmark", "Norwegia", "Finlandia"]},
    {"q": "Hallo", "a": "Belanda", "f": ["Jerman", "Denmark", "Belgia"]},
    {"q": "Merhaba", "a": "Turki", "f": ["Yunani", "Persia", "Arab"]},
    {"q": "Privet", "a": "Rusia", "f": ["Ukraina", "Polandia", "Belarus"]},
    {"q": "Shalom", "a": "Ibrani", "f": ["Arab", "Persia", "Yiddish"]},
    {"q": "Aloha", "a": "Hawaii", "f": ["Maori", "Samoa", "Tahiti"]},
]

COLORS = [
    {"q": "#FF0000", "a": "Merah", "f": ["Oranye", "Pink", "Magenta"]},
    {"q": "#00FF00", "a": "Hijau", "f": ["Cyan", "Kuning", "Lime"]},
    {"q": "#0000FF", "a": "Biru", "f": ["Ungu", "Cyan", "Indigo"]},
    {"q": "#FFFF00", "a": "Kuning", "f": ["Oranye", "Hijau", "Emas"]},
    {"q": "#FFA500", "a": "Oranye", "f": ["Merah", "Kuning", "Coklat"]},
    {"q": "#800080", "a": "Ungu", "f": ["Magenta", "Indigo", "Pink"]},
    {"q": "#FFC0CB", "a": "Pink", "f": ["Merah", "Magenta", "Salmon"]},
    {"q": "#A52A2A", "a": "Coklat", "f": ["Merah Marun", "Oranye", "Hitam"]},
    {"q": "#000000", "a": "Hitam", "f": ["Abu-abu", "Coklat tua", "Navy"]},
    {"q": "#FFFFFF", "a": "Putih", "f": ["Krem", "Abu-abu muda", "Perak"]},
    {"q": "#808080", "a": "Abu-abu", "f": ["Perak", "Putih", "Hitam"]},
    {"q": "#00FFFF", "a": "Cyan", "f": ["Biru", "Hijau", "Turquoise"]},
    {"q": "#FF00FF", "a": "Magenta", "f": ["Pink", "Ungu", "Merah"]},
    {"q": "#FFD700", "a": "Emas", "f": ["Kuning", "Oranye", "Krem"]},
    {"q": "#C0C0C0", "a": "Perak", "f": ["Abu-abu", "Putih", "Krem"]},
    {"q": "#000080", "a": "Navy", "f": ["Biru", "Indigo", "Hitam"]},
    {"q": "#008000", "a": "Hijau Tua", "f": ["Lime", "Olive", "Hijau Mint"]},
    {"q": "#800000", "a": "Maroon", "f": ["Merah", "Coklat", "Bordeaux"]},
]

EMOJI_PUZZLES = [
    {"q": "🦁👑", "a": "The Lion King", "f": ["Madagascar", "Jungle Book", "Tarzan"]},
    {"q": "❄️⛄👸", "a": "Frozen", "f": ["Tangled", "Cinderella", "Snow White"]},
    {"q": "🕷️🕸️👨", "a": "Spider-Man", "f": ["Batman", "Iron Man", "Venom"]},
    {"q": "⚡🧙", "a": "Harry Potter", "f": ["Lord of the Rings", "Doctor Strange", "Merlin"]},
    {"q": "🚢🧊💔", "a": "Titanic", "f": ["Pearl Harbor", "Pirates of the Caribbean", "Poseidon"]},
    {"q": "🦖🦕🏝️", "a": "Jurassic Park", "f": ["King Kong", "Land Before Time", "Godzilla"]},
    {"q": "🤖🚗", "a": "Transformers", "f": ["Cars", "Wall-E", "Robocop"]},
    {"q": "🐟🔍", "a": "Finding Nemo", "f": ["Shark Tale", "Moana", "Ponyo"]},
    {"q": "🍫🏭👦", "a": "Charlie and the Chocolate Factory", "f": ["Hansel and Gretel", "Wonka", "Matilda"]},
    {"q": "💍🌋", "a": "Lord of the Rings", "f": ["The Hobbit", "Game of Thrones", "Eragon"]},
    {"q": "👽📞🏠", "a": "E.T.", "f": ["Avatar", "Men in Black", "Stranger Things"]},
    {"q": "🏰🏰⚔️🐉", "a": "Game of Thrones", "f": ["Vikings", "The Witcher", "Lord of the Rings"]},
    {"q": "⚓🏴‍☠️", "a": "Pirates of the Caribbean", "f": ["One Piece", "Treasure Island", "Black Sails"]},
    {"q": "🥋🐢", "a": "Teenage Mutant Ninja Turtles", "f": ["Karate Kid", "Mulan", "Avatar"]},
    {"q": "🌙🐺", "a": "Twilight", "f": ["Underworld", "Wolf Man", "Van Helsing"]},
    {"q": "🍕🐢🥷", "a": "Teenage Mutant Ninja Turtles", "f": ["Kung Fu Panda", "Naruto", "Power Rangers"]},
    {"q": "🤡🎈", "a": "It", "f": ["Joker", "Batman", "Saw"]},
    {"q": "🦇🌃", "a": "Batman", "f": ["Daredevil", "Spider-Man", "Vampire"]},
    {"q": "🧪💊👨‍⚕️", "a": "Breaking Bad", "f": ["Better Call Saul", "Dexter", "House MD"]},
    {"q": "🚲🏠👦👽", "a": "E.T.", "f": ["Stranger Things", "Goonies", "Super 8"]},
]

YEARS = [
    {"q": "Tahun proklamasi kemerdekaan Indonesia.", "a": "1945", "f": ["1942", "1949", "1908"]},
    {"q": "Tahun runtuhnya Tembok Berlin.", "a": "1989", "f": ["1991", "1985", "1990"]},
    {"q": "Tahun manusia pertama mendarat di bulan.", "a": "1969", "f": ["1965", "1972", "1957"]},
    {"q": "Tahun Perang Dunia II berakhir.", "a": "1945", "f": ["1944", "1946", "1939"]},
    {"q": "Tahun reformasi Indonesia (jatuhnya Soeharto).", "a": "1998", "f": ["1996", "2000", "1997"]},
    {"q": "Tahun Soviet Union bubar.", "a": "1991", "f": ["1989", "1993", "1990"]},
    {"q": "Tahun pandemi COVID-19 dimulai global.", "a": "2020", "f": ["2019", "2021", "2018"]},
    {"q": "Tahun World Wide Web diciptakan.", "a": "1989", "f": ["1991", "1985", "1995"]},
    {"q": "Tahun iPhone pertama dirilis.", "a": "2007", "f": ["2005", "2008", "2010"]},
    {"q": "Tahun YouTube didirikan.", "a": "2005", "f": ["2003", "2007", "2006"]},
    {"q": "Tahun Sumpah Pemuda di Indonesia.", "a": "1928", "f": ["1908", "1945", "1920"]},
    {"q": "Tahun Titanic tenggelam.", "a": "1912", "f": ["1905", "1920", "1898"]},
    {"q": "Tahun Olimpiade pertama era modern.", "a": "1896", "f": ["1900", "1888", "1912"]},
    {"q": "Tahun Indonesia menjadi anggota PBB.", "a": "1950", "f": ["1945", "1955", "1949"]},
    {"q": "Tahun pendiri Microsoft (Bill Gates) lahir.", "a": "1955", "f": ["1950", "1960", "1948"]},
]

CHARACTERS = [
    {"q": "Detektif kecil dengan kacamata, jago tembak peluru bola sepak.", "a": "Conan Edogawa", "f": ["Kindaichi", "L Lawliet", "Sherlock"]},
    {"q": "Bajak laut bertopi jerami yang ingin jadi raja bajak laut.", "a": "Monkey D. Luffy", "f": ["Roronoa Zoro", "Portgas D. Ace", "Trafalgar Law"]},
    {"q": "Ninja berambut kuning dengan rubah ekor sembilan dalam tubuhnya.", "a": "Naruto Uzumaki", "f": ["Sasuke Uchiha", "Kakashi Hatake", "Minato Namikaze"]},
    {"q": "Saiyan berambut spike yang melawan Frieza di Namek.", "a": "Goku", "f": ["Vegeta", "Gohan", "Trunks"]},
    {"q": "Anak laki-laki dengan robot kucing dari masa depan.", "a": "Nobita", "f": ["Shinchan", "Ash Ketchum", "Pikachu"]},
    {"q": "Pelatih Pokemon dari Pallet Town.", "a": "Ash Ketchum", "f": ["Misty", "Brock", "Red"]},
    {"q": "Pemilik Death Note yang ingin jadi tuhan dunia baru.", "a": "Light Yagami", "f": ["L Lawliet", "Near", "Mello"]},
    {"q": "Anak nakal berumur 5 tahun dari Kasukabe.", "a": "Shinchan Nohara", "f": ["Doraemon", "Conan", "Pokemon"]},
    {"q": "Tikus kuning listrik partner dari pelatih Pokemon.", "a": "Pikachu", "f": ["Eevee", "Charmander", "Bulbasaur"]},
    {"q": "Anak SMA dengan note kematian dari shinigami.", "a": "Light Yagami", "f": ["Naruto", "Eren Yeager", "Lelouch"]},
    {"q": "Pembasmi titan dengan dendam besar pada raksasa.", "a": "Eren Yeager", "f": ["Levi Ackerman", "Mikasa Ackerman", "Armin Arlert"]},
    {"q": "Penyihir yang sekolah di Hogwarts dengan bekas luka petir.", "a": "Harry Potter", "f": ["Ron Weasley", "Hermione Granger", "Draco Malfoy"]},
    {"q": "Pendekar pedang slayer iblis dengan adik perempuan iblis.", "a": "Tanjiro Kamado", "f": ["Zenitsu Agatsuma", "Inosuke Hashibira", "Giyu Tomioka"]},
    {"q": "Pahlawan super dengan jubah merah dari planet Krypton.", "a": "Superman", "f": ["Batman", "Spider-Man", "Iron Man"]},
    {"q": "Putri Disney dengan rambut panjang ajaib di menara.", "a": "Rapunzel", "f": ["Elsa", "Cinderella", "Belle"]},
    {"q": "Putri es dari kerajaan Arendelle.", "a": "Elsa", "f": ["Anna", "Cinderella", "Aurora"]},
]

LYRICS = [
    {"q": "\"Pernahkah kau merasa, jarak antara kita...\"", "a": "Aku Pasti Kembali - Pance Pondaag", "f": ["Bahagia - Gamaliel", "Hingga Akhir Waktu - Nine Ball", "Kau Adalah - Isyana"]},
    {"q": "\"Cinta ini kadang-kadang tak ada logika...\"", "a": "Cinta - Vina Panduwinata", "f": ["Aku Bukan Untukmu - Rossa", "Cobalah Mengerti - Peterpan", "Asal Kau Bahagia - Armada"]},
    {"q": "\"Aku tidak takut kehilangan dirimu...\"", "a": "Asal Kau Bahagia - Armada", "f": ["Bukti - Virgoun", "Hanya Rindu - Andmesh", "Cinta Luar Biasa - Andmesh"]},
    {"q": "\"Hingga ujung waktu, takkan pernah lepas...\"", "a": "Hingga Ujung Waktu - Sheila on 7", "f": ["Melompat Lebih Tinggi - Sheila on 7", "Dan - Sheila on 7", "Pejantan Tangguh - Sheila on 7"]},
    {"q": "\"Kau begitu sempurna, di mataku kau begitu indah...\"", "a": "Sempurna - Andra and the Backbone", "f": ["Cinta Sejati - Bunga Citra Lestari", "Bukan Untukku - Rio Febrian", "Tak Ada Logika - Agnez Mo"]},
    {"q": "\"Apakah kau pernah merasa kasihku tak hanya untukmu...\"", "a": "Tetap Dalam Jiwa - Isyana Sarasvati", "f": ["Lagu Galau - 5 Romeo", "Cinta Putih - Katon", "Suara Hati - Inka Christie"]},
    {"q": "\"Cinta yang ku impikan, kasih yang ku harapkan...\"", "a": "Cinta - Melly Goeslaw", "f": ["Bunda - Melly Goeslaw", "Ada Apa Dengan Cinta - Melly", "Gantung - Melly Goeslaw"]},
    {"q": "\"Dan ku menanti, dan ku menanti, dan ku menanti...\"", "a": "Menanti - Sheila on 7", "f": ["Anugerah Terindah - Sheila on 7", "Pejantan Tangguh - Sheila on 7", "Berhenti Berharap - Sheila on 7"]},
    {"q": "\"Kalau kau tak ada di sisiku ku merasa sepi...\"", "a": "Lagu Cinta - Krisdayanti", "f": ["Mencintaimu - Krisdayanti", "Cobalah - Krisdayanti", "Cinta - Krisdayanti"]},
    {"q": "\"Cinta ini membunuhku, kau jauhkan diriku...\"", "a": "Cinta Ini Membunuhku - D'Masiv", "f": ["Jangan Menyerah - D'Masiv", "Diam Tanpa Kata - D'Masiv", "Pergilah Kasih - D'Masiv"]},
    {"q": "\"Now I'm at a payphone, trying to call home...\"", "a": "Payphone - Maroon 5", "f": ["Sugar - Maroon 5", "Memories - Maroon 5", "Girls Like You - Maroon 5"]},
    {"q": "\"Hello, it's me, I was wondering if after all these years...\"", "a": "Hello - Adele", "f": ["Someone Like You - Adele", "Rolling in the Deep - Adele", "Easy On Me - Adele"]},
    {"q": "\"I throw all of your stuff away, then I clear you out of my head...\"", "a": "Back to December - Taylor Swift", "f": ["All Too Well - Taylor Swift", "Style - Taylor Swift", "Blank Space - Taylor Swift"]},
    {"q": "\"We were both young when I first saw you...\"", "a": "Love Story - Taylor Swift", "f": ["You Belong With Me - Taylor Swift", "Wildest Dreams - Taylor Swift", "Cardigan - Taylor Swift"]},
    {"q": "\"Despacito, quiero respirar tu cuello despacito...\"", "a": "Despacito - Luis Fonsi", "f": ["Bailando - Enrique Iglesias", "La Bamba - Ritchie Valens", "Macarena - Los del Río"]},
]
